<?php
        $apiKey="rzp_test_PRasMuLPmFOHku";
        include('../connection.php');
        session_start();
        $session=$_SESSION['id'];
        $sqlii="SELECT user_reg.log_id,user_reg.fname,user_reg.phone,user_reg.address,user_reg.email,user_reg.id,tl_order.id,tl_order.ar_id,tl_order.price,tl_order.u_id from tl_order join user_reg on tl_order.u_id=user_reg.log_id where user_reg.log_id='$session'";
        $result = mysqli_query($con, $sqlii);
        while ($rows = mysqli_fetch_array($result)) {
            $vi=$rows['fname'];
            $ar=$rows['ar_id'];
            $email=$rows['email'];
      
  
 
         }
        $sr="SELECT price FROM tl_order where tl_order.u_id='$session'";
        $tt=mysqli_query($con,$sr);
        while ($rows = mysqli_fetch_array($tt)) {
           // $id= $row['id'];
            $amount=$rows['price'];
            // $name=$row['name'];

        }
       
?>



 
 <!DOCTYPE html>  
<html>  
<head>  
<meta name="viewport" content="width=device-width, initial-scale=1">  
<style>  
body {
  background:linear-gradient(to right, #78a7ba 0%, #385D6C 50%, #78a7ba 99%);
}
.container {  
    padding: 100px;  
  background-color: white;  
}  
  
input[type=text], input[type=password], textarea {  
  width: 100%;  
  padding: 15px;  
  margin: 5px 0 22px 0;  
  display: inline-block;  
  border: none;  
  background: #f1f1f1;  
}  
input[type=text]:focus, input[type=password]:focus {  
  background-color: gray;  
  outline: none;  
}  
 div {  
            padding: 10px 0;  
         }  
hr {  
  border: 1px solid #f1f1f1;  
  margin-bottom: 25px;  
}  
.registerbtn {  
  background-color: #4CAF50;  
  color: white;  
  padding: 16px 20px;  
  margin: 8px 0;  
  border: none;  
  cursor: pointer;  
  width: 100%;  
  opacity: 0.9;  
}  
.registerbtn:hover {  
  opacity: 1;  
} 
 
.button {
  border: none;
  color: white;
  padding: 10px 25px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;

}

.button1 {background-color: #4CAF50;} /* Green */
.button2 {background-color: #008CBA;} 
<style>
 @import url('https://fonts.googleapis.com/css2?family=Open+Sans&display=swap');  
body {  
font-family: 'Open Sans', sans-serif;  
margin: 0;  
}  
a {  
text-decoration: none;  
color: #FFFFFF;  
}  
a:hover{  
color: rgb(179, 179, 179);  
}  
.site-header {   
border-bottom: 1px solid #ccc; 
width:100%; 
height:80px; 
background:black; 
font-size:18px;
position:top;
padding: .0em 0em;  
display: flex;  
justify-content: space-between;   
}  
.site-identity h1 {  
font-size: 1.5em;  
margin: .6em 0;  
display: inline-block;  
}  
.site-navigation ul,   
.site-navigation li {  
margin: 0;   
padding: 0;  
}  
.site-navigation li {  
display: inline-block;  
margin: 1.4em 1em 1em 1em;  
}  
.product_wrapper {
	float:right;
	padding: 20px;
	text-align: center;
	}
</style>
</style> 
<style> form{
  padding: 100px 550px;
}</style> 
</head>
<?php
$id=$_SESSION['id'];
?>  
<body>  
<header class="site-header">  
     <div class="site-identity">  
      <h1><a href="#"></a></h1>  
     </div>   
     <nav class="site-navigation">  
      <ul class="nav">  
       <li><a href="index.php">Home</a></li>   
	   <li><a href="userprofile.php?id=<?php echo $username=$_SESSION['id']; ?>">Profile</a></li>
	   <li><a href="paintingsbook.php?id=<?php echo $username=$_SESSION['id']; ?>">Buy Paintings</a></li>
	   <li><a href="./table-09/userprogrambooking.php?id=<?php echo $username=$_SESSION['id']; ?>">My Bookings</a></li>
	 <!-- <li><a href="logout.php">Logout</a></li>												   -->
      </ul>  
     </nav>  
    </header> 
<form method="POST" action="orderaction.php?amount=<?php echo $amount; ?>&&ar=<?php echo $ar; ?>&&email=<?php echo $email; ?>">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $amount * 100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="<?php rand(100000, 999999);?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay Amount"
    data-name="Artsy"
    data-description="Add more colors to your day"
    data-image=""
    data-prefill.name="<?php echo $vi;?>"
    data-prefill.email=""
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
<!-- <input type="hidden" name="artist" value="<?php echo $ar; ?>">
<input type="hidden" name="amount" value="<?php echo $amount; ?>"> -->


</form>

<!--style>
.razorpay-payment-button { display:none; }
</style>


<script type="text/javascript">
  $(document).ready(function(){
    $('.razorpay-payment-button').click();

});
</script-->